<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nozzle.Samples.Receiver</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Nozzle.NET.csproj" />
  </ItemGroup>

</Project>
